manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/petejohanson
    # START #####
    - name: badjeff
      url-base: https://github.com/badjeff
    # END #######
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: feat/pointers-move-scroll
      import: app/west.yml
    # START #####
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main
    # END #######
  self:
    path: config
